name: Cypress API Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: npm ci

      - name: Ensure Cypress binary permissions
        run: chmod +x ~/.cache/Cypress/13.15.0/Cypress/Cypress

      - name: Install Cypress
        run: sudo npx cypress install

      - name: Create reports directory
        run: mkdir -p cypress/reports/mochawesome  # Directory for mochawesome reports

      - name: Run Cypress tests with Allure and MochaAwesome
        run: |
          sudo apt-get install -y xvfb
          xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" npx cypress run || true
          npx allure generate allure-results --clean  # Generate Allure report

      - name: Check for MochaAwesome reports
        run: |
          echo "Checking for MochaAwesome report files..."
          if ls cypress/reports/mochawesome/*.html 1> /dev/null 2>&1; then
            echo "MochaAwesome report files found:"
            ls -l cypress/reports/mochawesome/*.html
          else
            echo "No MochaAwesome reports found."
            exit 0
          fi

      - name: Zip Allure Report
        run: |
          npx allure generate allure-results --clean
          zip -r allure-report.zip allure-report

      - name: Archive Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report.zip

      - name: Send email notification with MochaAwesome report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Cypress Test Report(MochaAwesome) for ${{ github.repository }}
          body: "The Cypress test run for ${{ github.repository }} has completed. Check the attached report for detailed results."
          to: |
            oluwashola.olagbemisoye@mtn.com, 
            shola.olagbemisoye@wemabank.com, 
            olushola@ebsafr.com, 
            olawunmitolulope6@gmail.com
          from: shola.mich.7438@gmail.com
          attachments: cypress/reports/mochawesome/mochawesome.html  # Attach MochaAwesome report

      - name: Send Allure report via email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Cypress Test Report(Allure) for ${{ github.repository }}
          body: "The Cypress test run for ${{ github.repository }} has completed. Check the attached report for detailed results."
          to: |
            oluwashola.olagbemisoye@mtn.com, 
            shola.olagbemisoye@wemabank.com, 
            olushola@ebsafr.com, 
            olawunmitolulope6@gmail.com
          from: shola.mich.7438@gmail.com
          attachments: allure-report.zip  # Attach zipped Allure report
